import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { RelatedLinks } from "@/components/ContentCard";
import { freeTiers, getFreeTier, getPlatformById, platformSlug } from "@/lib/content";

export const dynamic = "force-static";
export function generateStaticParams() { return freeTiers.map((entry) => ({ slug: entry.slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const entry = getFreeTier(slug); const title = slug === "openrouter" ? "OpenRouter API Free Tier: Models, Limits & Pricing · APISpotlight" : entry ? `${entry.provider} Free Tier · APISpotlight` : ""; const description = slug === "openrouter" ? "OpenRouter API 免费额度、Free models、速率限制、注册条件与官方 Pricing 来源；包含最后核验日期和不确定项说明。" : entry ? `${entry.provider} 的免费额度、限制、注册条件、官方来源与最后核验日期。` : ""; return entry ? { title, description, alternates: { canonical: `/free-tier/${slug}/` }, openGraph: { url: `https://api-spotlight.pages.dev/free-tier/${slug}/`, title, description: entry.free_amount } } : {}; }); }

export default async function FreeTierPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const entry = getFreeTier(slug); if (!entry) notFound();
  const platform = entry.platform_id ? getPlatformById(entry.platform_id) : undefined;
  const platformPath = entry.platform_id ? platformSlug(entry.platform_id) : undefined;
  const facts: Array<[string, string]> = [["API / Service", entry.api_service], ["Unit", entry.unit], ["Reset Period", entry.reset_period], ["Rate Limits", entry.rate_limits], ["Credit Card", entry.credit_card], ["Sign-up", entry.signup], ["Expiration", entry.expiration], ["Verification", `${entry.last_verified} · ${entry.verification_status} · ${entry.confidence} confidence`]];
  const heading = slug === "openrouter" ? "OpenRouter API Free Tier：免费模型、限制与注册条件" : `${entry.provider} Free Tier`;
  return <div className="mx-auto max-w-4xl px-4 py-12"><Link href="/free-tier" className="text-sm text-foreground/60 hover:text-foreground">← 返回 Free Tier</Link><main className="mt-8"><p className="font-mono text-xs uppercase tracking-widest text-emerald-600 dark:text-emerald-400">Free Tier / {entry.slug}</p><h1 className="mt-3 text-3xl font-bold">{heading}</h1><p className="mt-4 text-lg leading-8 text-foreground/75">{entry.free_amount}</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{facts.map(([label, value]) => <div key={label} className="rounded-xl border border-foreground/10 p-4"><p className="text-xs text-foreground/50">{label}</p><p className="mt-2 text-sm leading-6">{value}</p></div>)}</div><section className="mt-8 rounded-xl border border-foreground/10 p-5"><h2 className="font-semibold">Restrictions</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-foreground/70">{entry.restrictions.map((item) => <li key={item}>· {item}</li>)}</ul></section><section className="mt-8 rounded-xl border border-foreground/10 p-5"><h2 className="font-semibold">Official sources</h2><div className="mt-3 space-y-2 text-sm"><External href={entry.official_website_url} label="官方网站"/><External href={entry.official_documentation_url} label="官方文档"/><External href={entry.official_pricing_url} label="官方定价/福利说明"/></div><p className="mt-4 text-xs leading-5 text-foreground/50">Source type：{entry.source_type}。本站不把博客或旧文章当作当前额度证明。</p></section>{platform && platformPath && <section className="mt-8 rounded-xl border border-foreground/10 p-5"><h2 className="font-semibold">Provider page</h2><Link href={`/platform/${platformPath}`} className="mt-3 inline-block text-sm underline underline-offset-4">查看平台能力、Benchmark 与推荐用法 →</Link></section>}<section className="mt-8"><h2 className="font-semibold">Related developer resources</h2><div className="mt-3"><RelatedLinks resourceSlugs={entry.related_resource_slugs}/></div></section></main></div>;
}

function External({ href, label }: { href: string; label: string }) { return <a href={href} target="_blank" rel="noopener noreferrer" className="block underline underline-offset-4 hover:text-emerald-600">{label} ↗</a>; }
